services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web/static
      - media-data:/vol/web/media
      - sqlite-data:/quizapp
    environment:
      # - DB_HOST=db
      # - DB_NAME=${DB_NAME}
      # - DB_USER=${DB_USER}
      # - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DEBUG=1
    # depends_on:
    #   - db

  # db:
  #   image: postgres:13-alpine
  #   restart: always
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
      - 443:443
    volumes:
      - static-data:/vol/static
      - media-data:/vol/media
      - certbot-etc:/etc/letsencrypt
      - certbot-web:/var/www/certbot

    environment:
      - SER_NAME=${NGINX_SERVER_NAME}
      - CRT_DNS=${CRT_DNS_ENV}
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-web:/var/www/certbot
    entrypoint: "/bin/sh -c"
    command: >
      certbot certonly --webroot --webroot-path=/var/www/certbot
      --email sivanishasa@gmail.com --agree-tos --no-eff-email
      -d neotechwave.net -d www.neotechwave.net --non-interactive

volumes:
  # postgres-data:
  static-data:
  media-data:
  sqlite-data:
  certbot-etc:
  certbot-web:
